title: Jenn Ubaldo
logo: "/images/Jenn-Profile-opt-blue.png"
description: "Hi, I'm Jenn! 👋<br>
🌟 I’m currently diving deeper into coding for data science and analytics."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
